tisdk-display-cluster-image: remove weston from the filesystem
TexasInstruments/meta-tisdk pull request #30
Opened 2024-07-25 08:29 UTC by sskartheekadivi

2024-07-26 10:44 UTC, cshilwant reviewed
Let's build test & verify whether this drops all references of weston from filesystem or not

2024-07-26 10:46 UTC, cshilwant requested changes
Marking it as Needs Work until build test.

2025-03-30 14:49 UTC, cshilwant commented
@jeevantelukula Is this PR still relevant?

Expecting your PR - https://github.com/TexasInstruments/meta-tisdk/pull/69 to handle the same

2025-04-01 06:22 UTC, jeevantelukula commented
Yes. PR- #69  handles the weston launch issue in display cluster. Boot Logs are attached here.

https://gist.githubusercontent.com/jeevantelukula/9f550d184f556c768afc71bdfb51ee87/raw/14e4d62c639bbf25385dd8d92ca5355d7f11c05c/gistfile1.txt

2025-04-01 08:35 UTC, closed without merging

2025-04-01 08:35 UTC, cshilwant commented
@jeevantelukula Thanks for confirming. 
Closing as per https://github.com/TexasInstruments/meta-tisdk/pull/30#issuecomment-2768291570